[project]
name = "sysinit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accessify>=0.3.1",
    "black>=25.1.0",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
]

[tool.black]
line-length = 120
